const events = [
  { event: "Franz Beckenbauer veröffentlicht seinen Musikhit \"Gute Freunde kann niemand trennen\"", year: 1966 },
  { event: "Ferenc Puskás wird geboren", year: 1927 },
  { event: "Das neue Sportmagazin \"kicker\" veröffentlicht seine Erstausgabe", year: 1920 },
  { event: "Das neue Fußballmagazin \"11Freunde\" veröffentlicht seine Erstausgabe", year: 2000 },
  { event: "Die \"Sportschau\" feiert seine Erstausstrahlung im ZDF", year: 1952 },
  { event: "Die Talkshow \"Doppelpass\" feiert seine Erstausstrahlung auf Sport1", year: 1991 },
  { event: "Die Partie zwischen dem SV Werder Bremen und dem 1.FC Köln wird als erstes Bundesliga-Spiel live im Fernsehen übertragen", year: 1969 },
  { event: "Lothar Matthäus heiratet seine Erste (von Fünf) Ehefrau Marianne", year: 1981 },
  { event: "Cristiano Ronaldo versteckt während einer Pressekonferenz mit Portugal Produkte des Turniersponsors \"Coca Cola\" und sorgt damit für Aufsehen", year: 2021 },
  { event: "Philipp Lahm beendet seine aktive Laufbahn", year: 2017 },
  { event: "Thomas Hitzelsperger outet sich als Erster ehemaliger deutscher Nationalspieler als homosexuell", year: 2014 },
  { event: "Uli Hoeneß wird wegen Steuerhinterziehung in Höhe von über 28 Mio. € zu einer Haftstrafe von 3,5 Jahren verurteilt", year: 2014 },
  { event: "FC Bayern München-Profi Breno wird wegen Brandstiftung zu einer Haftstrafe von 3 Jahren und 9 Monaten verurteilt", year: 2012 },
  { event: "Robert Enke nimmt sich im Alter von 32 Jahren das Leben", year: 2009 },
  { event: "Die Mannschaft des brasilianischen Erstligisten Chapocoense stürzt über den Bergen von Kolumbien ab", year: 2016 },
  { event: "Die Mannschaft von Manchester United stürzt bei der Landung auf dem Flughafen München-Riem ab", year: 1958 },
  { event: "Der Fan-Song \"Es gibt nur ein Rudi Völler\" wird veröffentlicht", year: 2002 },
  { event: "Die FIFA vergibt die Weltmeisterschaft 2022 nach Katar", year: 2010 },
  { event: "Petr Čech verletzt sich gegen den FC Reading und beschließt fortan nur noch mit Helm zu spielen", year: 2006 },
  { event: "Der russische Oligarch Roman Abramovich kauft den FC Chelsea", year: 2003 },
  { event: "Die Fußball-Website \"transfermarkt.de\" geht erstmals online", year: 2000 },
  { event: "Das erste FIFA-Videospiel von EA Sports kommt auf den Markt", year: 1993 },
  { event: "DFB-Präsident Wolfgang Niersbach tritt nach der \"Uhr-Affäre\" von seinen Ämtern zurück", year: 2015 },
  { event: "Das \"Aktuelle Sportstudio\" feiert seine Erstausstrahlung im damaligen NWDR", year: 1963 },
  { event: "Jan Koller muss ab der 67. im Bundesliga-Spiel gegen den FC Bayern München ins Tor - er pariert ohne Fehler", year: 2002 },
  { event: "Der FC St. Pauli steigt zum ersten Mal in die 1. Bundesliga auf ", year: 1976 },
  { event: "Franck Ribéry wechselt zum FC Bayern München", year: 2007 },
  { event: "Hennes I. tritt zum ersten Mal als Maskottchen des 1.FC Köln auf", year: 1950 },
  { event: "Die rote Karte wird in der Bundesliga eingeführt", year: 1970 },
  { event: "Die Bundesliga führt eine Spielsperre nach der fünften gelben Karte ein", year: 1991 },
  { event: "Christian Eriksen kollabiert auf dem Spielfeld aufgrund eines plötzlichen Herztods und überlebt nur knapp", year: 2021 },
  { event: "Andreas Möller wechselt vom FC Schalke 04 zu Rivale Borussia Dortmund und wird dadurch zur Hassfigur", year: 2000 },
  { event: "Youssoufa Moukoko debütiert mit 15 Jahren und 364 Tagen in der Bundesliga für Borussia Dortmund", year: 2020 },
  { event: "Gianluigi Donnarumma debütiert mit 16 Jahren für den AC Mailand in der Serie A", year: 2015 },
  { event: "Borussia Mönchengladbach besiegt Borussia Dortmund in der Bundesliga mit 12:0", year: 1978 },
  { event: "Oliver Kahn wird von einem Fan des SC Freiburg mit einem Golfball im Gesicht getroffen", year: 2000 },
  { event: "Paolo Guerrero grätscht Torhüter Sven Ulreich an der Eckfahne hüfthoch um und erhält eine Sperre von acht Spielen", year: 2012 },
  { event: "Die SK Rapid Wien gewinnt den Vorgänger des heutigen DFB-Pokals (Tschammer-Pokal)", year: 1939 },
  { event: "Der angetrunkene Schiedsrichter Wolf-Dieter Ahlenfelder pfeift im Bundesliga-Spiel zwischen dem SV Werder Bremen und Hannover 96 bereits nach 32 Minuten zur Halbzeit", year: 1975 },
  { event: "Jens Lehmann pinkelt beim Spiel vom VfB Stuttgart gegen Bayer 04 Leverkusen, nachdem er hinter die Werbebande geklettert ist, hinter die Werbetonne", year: 2009 },
  { event: "Max Kruse gewinnt 75.000€ beim Poker spielen und vergisst es kurz darauf im Taxi", year: 2016 },
  { event: "Deutschland gewinnt den Confed-Cup", year: 2017 },
  { event: "Dani Alves wird Opfer eines rassistischen Vorfalls im Spiel FC Villareal gegen den FC Barcelona, indem er mit Bananen beworfen wird. Er isst diese kurzerhand einfach", year: 2014 },
  { event: "Der FC Bayern München beruft eine Pressekonferenz ein – um Journalisten für Kritik an Spielern öffentlich zu rügen", year: 2018 },
  { event: "Christoph Daum willigt aufgrund seines \"absolut reinem Gewissen\" einem Drogentest zu, der sich als postiv herausstellt", year: 2000 },
  { event: "Giovanni Trappatoni hält eine Wutrede bei einer Pressekonferenz, in der legendäre Zitate wie \"Was erlauben Strunz?\" oder \"Ich habe fertig!\"", year: 1998 },
  { event: "Die Italiener laufen als politisches Statement für Mussolini bei einer WM im schwarzen Trikot auf", year: 1938 },
  { event: "Arjen Robben wechselt zum FC Bayern München", year: 2009 },
  { event: "Die umstrittene Bronzestatue am Flughafen Madeiras von Cristiano Ronaldo wird enthüllt", year: 2017 },
  { event: "Neymar wechselt zum FC Barcelona", year: 2013 },
  { event: "Paul, die Krake sagte bei einer WM alle Deutschland-Spiele korrekt voraus", year: 2010 },
  { event: "Uruguays José Batista sieht im WM-Spiel gegen Schottland nach 56 Sekunden die Rote Karte – bis heute Rekord", year: 1986 },
  { event: "Andrés Iniesta wechselt zu Vissel Kobe", year: 2018 },
  { event: "Sergej W. verübt einen Anschlag auf den Mannschaftsbus von Borussia Dortmund", year: 2017 },
  { event: "Gerd Müller absolviert sein letztes Bundesliga-Spiel für den FC Bayern München", year: 1979 },
  { event: "Lionel Messi holt seinen allerersten Champions-League-Titel", year: 2006 },
  { event: "Lionel Messi wird mit Argentinien zum ersten Mal Weltmeister", year: 2022 },
  { event: "Cristiano Ronaldo wird mit Portugal zum ersten Mal Europameister", year: 2016 },
  { event: "Luis Figo wechselt vom FC Barcelona zum Ligarivalen Real Madrid", year: 2000 },
  { event: "Deutschland wird zum zweiten Mal Weltmeister", year: 1974 },
  { event: "Spanien wird zum ersten Mal Europameister", year: 1964 },
  { event: "Spanien wird zum ersten Mal Weltmeister", year: 2010 },
  { event: "Fabio Cannavaro gewinnt den Ballon D'Or", year: 2006 },
  { event: "Manuel Neuer wechselt vom FC Schalke 04 zum FC Bayern München", year: 2011 },
  { event: "Pelé schießt sein allererstes Länderspieltor", year: 1957 },
  { event: "Miroslav Klose feiert sein Länderspiel-Debüt für Deutschland", year: 2001 },
  { event: "Brasilien wird zum fünften Mal Weltmeister", year: 2002 },
  { event: "Eden Hazard wechselt vom FC Chelsea London zu Real Madrid", year: 2019 },
  { event: "Kylian Mbappé wechselt von Paris St. Germain zu Real Madrid", year: 2024 },
  { event: "Joachim Löw wird Cheftrainer der deutschen Nationalmannschaft", year: 2006 },
  { event: "Jürgen Klopp wird Cheftrainer vom FC Liverpool", year: 2015 },
  { event: "Thomas Tuchel wird Cheftrainer vom FC Bayern München", year: 2023 },
  { event: "Pep Guardiola wird Cheftrainer vom FC Barcelona", year: 2008 },
  { event: "Lamine Yamal macht sein Profi-Debüt für den FC Barcelona", year: 2023 },
  { event: "Deutschland besiegt Costa Rica bei einem Fußball-Weltmeisterschaftsspiel mit 4:2", year: 2022 },
  { event: "Südafrika ist Gastgeber einer Fußball-Weltmeisterschaft", year: 2010 },
  { event: "Borussia Dortmund gewinnt zum ersten Mal die Deutsche Meisterschaft", year: 1956 },
  { event: "Bayer 04 Leverkusen gewinnt zum ersten Mal die Bundesliga-Meisterschaft", year: 2024 },
  { event: "Uruguay wird zum ersten Mal Fußball-Weltmeister", year: 1930 },
  { event: "Der Videobeweis (VAR) kommt zum ersten Mal bei einer Fußball-Weltmeisterschaft zum Einsatz", year: 2018 },
  { event: "Just Fontaine trifft zwölf Mal bei einer Fußball-Europameisterschaft", year: 1960 },
  { event: "Gianni Infantino wird neu zum FIFA-Präsidenten gewählt", year: 2016 },
  { event: "Julian Nagelsmann wird Cheftrainer der deutschen Nationalmannschaft", year: 2023 },
  { event: "Deutschland besiegt Argentinien in einem WM-KO-Spiel mit 4:0", year: 2010 },
  { event: "Diego Maradona wird Cheftrainer der argentinischen Nationalmannschaft", year: 2008 },
  { event: "Carlo Ancelotti wird Cheftrainer der brasilianischen Nationalmannschaft", year: 2025 },
  { event: "Die neugegründete Youth-League geht erstmals an den Start", year: 2013 },
  { event: "Iker Casillas beendet seine aktive Laufbahn", year: 2020 },
  { event: "Marc-André ter Stegen wechselt zum FC Barcelona", year: 2014 },
  { event: "Leicester City gewinnt sensationell die Premier League", year: 2016 },
  { event: "Der VfL Wolfsburg gewinnt zum ersten Mal unter Felix Magath die Bundesliga", year: 2009 },
  { event: "Die erste Bundesliga-Saison wird ausgetragen", year: 1963 },
  { event: "Die erste Serie A Saison wird ausgetragen", year: 1929 },
  { event: "Thomas Müller feiert sein Bundesliga-Debüt für den FC Bayern München", year: 2008 },
  { event: "Pep Guardiola wird Cheftrainer des FC Bayern München", year: 2013 },
  { event: "Kevin Großkreutz bewirft einen Fußball-Fan mit einem Döner", year: 2014 },
  { event: "Juventus Turin gewinnt zum ersten Mal die Serie A", year: 1905 },
  { event: "Inter Mailand gewinnt zum ersten Mal die Serie A", year: 1910 },
  { event: "Olympique Lyon gewinnt zum ersten Mal die Ligue 1", year: 2002 },
  { event: "Paris St. Germain gewinnt zum ersten Mal die Ligue 1", year: 1986 },
  { event: "Cristiano Ronaldo wechselt nach Saudi-Arabien", year: 2023 },
  { event: "Stéphanie Frappart pfeift als erste Frau ein WM-Spiel der Männer", year: 2022 },
  { event: "Der FC Bayern München gewinnt zum ersten Mal eine Bundesliga-Meisterschaft", year: 1969 },
  { event: "Cristiano Ronaldo holt seinen allerersten Champions-League-Titel", year: 2008 },
  { event: "Der FC Bayern München wird gegründet", year: 1900 },
  { event: "Lionel Messi verlässt den FC Barcelona", year: 2021 },
  { event: "Cristiano Ronaldo verlässt Real Madrid", year: 2018 },
  { event: "Real Madrid gewinnt die Champions-League zum 14. Mal", year: 2022 },
  { event: "Alexia Putellas gewinnt zum ersten Mal den Ballon D'Or", year: 2021 },
  { event: "Der TSV 1860 München gewinnt zum ersten Mal die Bundesliga", year: 1966 },
  { event: "Der FC Bayern München stellt mit 101 Toren einen Torrekord in der Bundesliga auf", year: 1972 },
  { event: "Kevin Keegan wechselt zum Hamburger SV", year: 1977 },
  { event: "Zlatan Ibrahimović trifft im Freundschaftsspiel gegen England per Fallrückzieher aus ca. 35 Metern", year: 2012 },
  { event: "Deutschland wird zum zweiten Mal Weltmeister", year: 1974 },
  { event: "Pelé schießt sein allererstes Länderspieltor", year: 1957 },
  { event: "Der FC Barcelona dreht in der Champions-League gegen Paris St. Germain eine 4:0-Hinspielniederlage und gewinnt mit 6:1", year: 2017 },
  { event: "Eric Cantona wird nach einem Kung-Fu-Tritt gegen einen Fan für 8 Monate gesperrt", year: 1995 },
  { event: "Lionel Messi trifft kurz vor Schluss im El Clásico und hält sein Trikot vor der Real-Madrid-Kurve in die Luft", year: 2017 },
  { event: "Robin van Persie trifft per Flugkopfall als „fliegender Holländer“ gegen Spanien zum 1:1", year: 2014 },
  { event: "Ronaldinho trifft per Lupfer von der Mittellinie gegen England", year: 2002 },
  { event: "Luis Suárez beißt Georgio Chiellini bei einem WM-Spiel", year: 2014 },
  { event: "Antonin Panenka prägt mit seinem kunstvollen Elfmeter bei einer Europameisterschaft ganze Generationen", year: 1976 },
  { event: "Kroatien zieht in sein erstes WM-Finale ein", year: 2018 },
  { event: "England gewinnt gegen Kolumbien erstmals ein Elfmeterschießen bei einer Weltmeisterschaft", year: 2018 },
  { event: "Eintracht Frankfurt gewinnt gegen die Glasgow Rangers die Europa-League", year: 2022 },
  { event: "Paris St. Germain gewinnt zum ersten Mal die Champions-League", year: 2025 },
  { event: "Der FC Bayern München gewinnt zum ersten Mal das Sextuple", year: 2020 },
  { event: "Deutschland besiegt die Türkei im Halbfinale einer Europameisterschaft im Elfmeterschießen", year: 2008 },
  { event: "Sami Khedira feiert sein Debüt für die deutsche Nationalmannschaft", year: 2009 },
  { event: "Der FC Bayern München besiegt Borussia Dortmund im deutschen Champions-League-Finale", year: 2013 },
  { event: "Manchester United besiegt den FC Bayern München dank zwei Treffer in der Nachspielzeit", year: 1999 },
  { event: "Spanien wird U17-, U21- und A-Nationalmannschaft-Europameister im gleichen Jahr", year: 2024 }
];
