const events = [
{ event: "Franz Beckenbauer veröffentlicht seinen Musikhit \"Gute Freunde kann niemand trennen\"", year: 1966 },
{ event: "MagentaTV überträgt erstmals eine Europameisterschaft", year: 2024 },
{ event: "DAZN ist erstmals in Deutschland verfügbar", year: 2016 },
{ event: "Der neue Streaming-Dienst WOW löst das alte Sky Ticket ab", year: 2022 },
{ event: "Thorsten Legat nimmt erstmals bei \"Ich bin ein Star - Holt mich hier raus\" teil", year: 2016 },
{ event: "Rudi Assauer stirbt", year: 2019 },
{ event: "Uli Hoeneß kritisiert Juan Bernat und bezeichnet seine Leistung als \"Scheißdreck\"" },
{ event: "Qatar Airways wird Sponsor des FC Bayern München", year: 2018 },
{ event: "Roman Abramowitsch verkauft Chelsea F.C.", year: 2022 },
{ event: "Mykhailo Mudryk wird aufgrund eines positiven Dopingtests gesperrt", year: 2024 },
{ event: "Paul Pogba wird aufgrund eines positiven Dopingtests gesperrt", year: 2023 },
{ event: "André Onana wird aufgrund eines positiven Dopingtests gesperrt", year: 2021 },
{ event: "Die Glasgow Rangers müssen aufgrund massiver Steuerschulden und einer Insolvenz in die 4. schottische Liga zwangsabsteigen", year: 2012 },
{ event: "Borussia Dortmund und der FC Schalke 04 treffen im 100. Revierderby aufeinander", year: 2023 },
{ event: "Der 1. FC Nürnberg und die SpVgg Greuther Fürth treffen im 200. Frankenderby aufeinander", year: 2011 },
{ event: "Das \"Jahrhundertspiel\" zwischen Deutschland und Italien findet in Mexiko statt", year: 1970 },
{ event: "Gianluigi Buffon beendet seine Profikarriere", year: 2023 },
{ event: "Iker Casillas beendet seine Profikarriere", year: 2020 },
{ event: "Edwin van der Sar beendet seine Profikarriere", year: 2011 },
{ event: "Petr Čech beendet seine Profikarriere", year: 2019 },
{ event: "Diego Simeone wird Cheftrainer von Atletico Madrid", year: 2011 },
{ event: "Fernando Torres beendet seine Profikarriere", year: 2019 },
{ event: "Fernando Torres wechselt für 50 Mio. Pfund zum Chelsea F.C.", year: 2011 },
{ event: "David Villa beendet seine Profikarriere", year: 2020 },
{ event: "David Villa wechselt zum FC Barcelona", year: 2010 },
{ event: "Das UNICEF-Logo erscheint erstmals auf dem Trikot des FC Barcelona", year: 2006 },
{ event: "Johan Cruyff verstirbt", year: 2016 },
{ event: "Thibault Courtois hat eine Affäre mit der Freundin von Kevin De Bruyne", year: 2013 },
{ event: "John Terry hat eine Affäre mit der Freundin seines Teamkollegen Wayne Bridge", year: 2010 },
{ event: "Günther Netzer und Gerhard Delling treten erstmals als Duo in der ARD auf", year: 1998 },
{ event: "Oliver Kahn debütiert in der 1. Bundesliga", year: 1987 },
{ event: "Fortuna Düsseldorf gewinnt die deutsche Meisterschaft", year: 1933 },
{ event: "Mirko Slomka führt Hannover 96 erstmals in die Europa League", year: 2011 },
{ event: "Beim Relegationsspiel gegen Hertha BSC stürmen Fans von Fortuna Düsseldorf vor Abpfiff den Rasen und sorgen für eine längere Spielunterbrechung", year: 2012 },
{ event: "Der VAR greift nach einem Handspiel von Kempf kurz vor der Halbzeit ein, obwohl Mainz 05 und Freiburg bereits in den Kabinen sind", year: 2018 },
{ event: "Ailton feiert sein Comeback in Deutschland und schließt sich Hassia Bingen an", year: 2012 },
{ event: "Cafù wechselt erstmals nach Europa zur AS Rom", year: 1997 },
{ event: "Kaká gewinnt den Ballon d'Or", year: 2007 },
{ event: "Lionel Messi gewinnt seinen ersten Ballon d'Or", year: 2009 },
{ event: "Cristiano Ronaldo gewinnt seinen ersten Ballon d'Or", year: 2008 },
{ event: "Michael Owen gewinnt den Ballon d'Or", year: 2001 },
{ event: "Andriy Shevchenko gewinnt den Ballon d'Or", year: 2004 },
{ event: "Pavel Nedvěd gewinnt den Ballon d'Or", year: 2003 },
{ event: "Rivaldo gewinnt den Ballon d'Or", year: 1999 },
{ event: "Usain Bolt absolviert ein zweitägiges Probetraining bei Borussia Dortmund", year: 2018 },
{ event: "George Weah gewinnt den Ballon d'Or", year: 1995 },
{ event: "Paolo Rossi gewinnt den Ballon d'Or", year: 1982 },
{ event: "Gerd Müller gewinnt den Ballon d'Or", year: 1970 },
{ event: "Lev Yashin gewinnt den Ballon d'Or", year: 1963 },
{ event: "Sir Stanley Matthews gewinnt den ersten Ballon d'Or der Geschichte", year: 1956 },
{ event: "Oleg Blokhin gewinnt den Ballon d'Or", year: 1975 },
{ event: "Marie-Louise Eta wird die erste weibliche Cheftrainerin der 1. Bundesliga", year: 2026 },
{ event: "Gerd Müller erzielt sein 300. Bundesliga Tor", year: 1976 },
{ event: "Kylian Mbappé wechselt für 180 Mio. € zu Paris St. Germain", year: 2018 },
{ event: "Alexander Isak wechselt für 145 Mio. € zum FC Liverpool", year: 2025 },
{ event: "Philippe Coutinho wechselt für 135 Mio. € zum FC Barcelona", year: 2017 },
{ event: "Jude Bellingham wechselt für 127 Mio. € zu Real Madrid", year: 2023 },
{ event: "Enzo Fernandez wechselt für 121 Mio. € zum Chelsea F.C.", year: 2023 },
{ event: "Cristiano Ronaldo wechselt für 117 Mio. € zu Juventus Turin", year: 2018 },
{ event: "Cristiano Ronaldo wechselt für 94 Mio. € zu Real Madrid", year: 2009 },
{ event: "Kai Havertz wechselt für 100 Mio. € zum Chelsea F.C.", year: 2020 },
{ event: "Jack Grealish wechselt für 117,50 Mio. € zu Manchester City", year: 2021 },
{ event: "Florian Wirtz wechselt für 125 Mio. € zum FC Liverpool", year: 2025 },
{ event: "Declan Rice wechselt für 116,60 Mio. € zum FC Arsenal", year: 2023 },
{ event: "João Félix wechselt für 127,20 Mio. € zu Atletico Madrid", year: 2019 },
{ event: "Gareth Bale wechselt für 101 Mio. € zu Real Madrid", year: 2013 },
{ event: "Gerard Piqué führt in Spanien seine Kings League ein", year: 2022 },
{ event: "Nach Schmähplakaten gegen Dietmar Hopp kommt es zu einer Spielunterbrechung, danach passen sich die Teams aus Protest nur noch den Ball zu", year: 2020 },
{ event: "Deutschland unterliegt Italien bei der Heim-WM in der Verlängerung", year: 2006 },
{ event: "Cristiano Ronaldo erzielt 17 Tore in einer Champions-League-Saison", year: 2014 },
{ event: "Lionel Messi führt Argentinien zum Copa-America-Titel", year: 2021 },
{ event: "Erling Haaland erzielt bei einer U20-WM gegen Honduras 9 Tore in einem Spiel", year: 2019 },
{ event: "Martin Ødegaard wechselt mit 16 Jahren zu Real Madrid", year: 2015 },
{ event: "Arda Güler wechselt zu Real Madrid", year: 2023 },
{ event: "Manuel Neuer feiert sein Debüt in der Champions League" },
{ event: "Samuel Eto'o wechselt zum FC Barcelona" },
{ event: "Der ehemalige FC Barcelona Trainer Ernesto Valverde verstirbt" },
{ event: "Mehrere Vereine rufen eine Super League aus, was große Fanproteste hervorruft" },
{ event: "Miroslav Klose wird WM-Rekordtorschütze", year: 2014 },
{ event: "Deutschland besiegt Brasilien im WM-Halbfinale mit 7:1", year: 2014 },
{ event: "Günter Netzer wechselt sich im DFB-Pokalfinale selbst ein und erzielt das Siegtor", year: 1973 },
{ event: "Nach einem hitzigen Handshake geraten Antonio Conte und Thomas Tuchel aneinander", year: 2022 },
{ event: "Die Elfenbeinküste verlässt aus Protest beim Afrika-Cup-Finale den Platz", year: 2026 },
{ event: "Die FIFA erkennt der Elfenbeinküste einen Afrika-Cup-Titel nachträglich ab und spricht ihn Marokko zu", year: 2026 },
{ event: "Salomon Kalou startet heimlich einen Livestream aus der Hertha-Kabine während Corona-Regeln gelten", year: 2020 },
{ event: "Dnipro Dnipropetrovsk muss sich wegen finanzieller Probleme auflösen", year: 2019 },
{ event: "Der SV Tasmania Berlin löst sich aufgrund finanzieller Probleme auf", year: 1973 },
{ event: "Hasan Ismaik steigt als Mehrheitseigner beim TSV 1860 München ein", year: 2011 },
{ event: "Adrian Mutu wird bei Chelsea positiv auf Kokain getestet und gesperrt", year: 2004 },
{ event: "Rio Ferdinand verpasst einen Drogentest und wird gesperrt", year: 2003 },
{ event: "Sandro Tonali wird wegen Wettvergehen für 10 Monate gesperrt", year: 2023 },
{ event: "Deniz Undav debütiert für den SV Meppen im Profifußball", year: 2018 },
{ event: "Fortuna Düsseldorf steigt in die Oberliga ab", year: 2002 },
{ event: "Der Karlsruher SC wird erstmals deutscher Meister", year: 1909 },
{ event: "Der Karlsruher SC gelingt im \"Wunder vom Wildpark\" ein 7:0 gegen Valencia", year: 1993 },
{ event: "Winfried Schäfer wird Trainer des Karlsruher SC und prägt die \"Euro-Eddy\"-Zeit", year: 1986 },
{ event: "Frank Schmidt wird Cheftrainer des 1. FC Heidenheim", year: 2007 },
{ event: "Der VfL Bochum steigt erstmals in die Bundesliga auf", year: 1971 },
{ event: "Das Ruhrstadion wird in Vonovia Ruhrstadion umbenannt", year: 2016 },
{ event: "Wiesenhof wird Hauptsponsor von Werder Bremen", year: 2012 },
{ event: "Der 1. FC Magdeburg gewinnt den Europapokal der Pokalsieger gegen den AC Mailand", year: 1974 },
{ event: "Jürgen Sparwasser erzielt das 1:0 für die DDR gegen die BRD", year: 1974 },
{ event: "Dynamo Dresden wird nach Fanausschreitungen für 2 Jahre aus Europa gesperrt", year: 1989 },
{ event: "Eritrea kehrt in den internationalen Fußball zurück und mehrere Spieler setzen sich ab", year: 2026 },
{ event: "Thomas Müller wechselt zu den Vancouver Whitecaps", year: 2025 },
{ event: "Neymar wechselt für 222 Mio. € zu Paris St. Germain", year: 2017 },
{ event: "Carlo Ancelotti wird brasilianischer Nationaltrainer", year: 2024 },
{ event: "Marokko erreicht als erste afrikanische Mannschaft ein WM-Halbfinale", year: 2022 },
{ event: "Schweden wird Vize-Weltmeister", year: 1958 },
{ event: "Dänemark wird überraschend Europameister", year: 1992 },
{ event: "Der Irak wird Asienmeister", year: 2007 },
{ event: "Bulgarien erreicht erstmals ein WM-Halbfinale", year: 1994 },
{ event: "Sambia wird Afrikameister", year: 2012 },
{ event: "Griechenland wird Europameister", year: 2004 },
{ event: "Beim WM-Gruppenspiel zwischen Deutschland und Österreich ereignet sich die Schande von Gijon", year: 1982 },
{ event: "Frank Lampards Wembley Tor gegen Deutschland wird nicht gegeben", year: 2010 },
{ event: "Island schlägt England bei einer Europameisterschaft", year: 2016 },
{ event: "Inter Mailand gewinnt unter José Mourinho das Triple", year: 2010 },
{ event: "Stefan Kießling wird Torschützenkönig der Bundesliga", year: 2013 },
{ event: "Marek Mintál wird Torschützenkönig der Bundesliga", year: 2005 },
{ event: "Ailton wird Torschützenkönig der Bundesliga", year: 2004 },
{ event: "Theofanis Gekas wird Torschützenkönig der Bundesliga", year: 2007 },
{ event: "Luca Toni wird Torschützenkönig der Bundesliga", year: 2008 },
{ event: "Mario Basler wird Torschützenkönig der Bundesliga", year: 1995 },
{ event: "Sergej Barbarez wird Torschützenkönig der Bundesliga", year: 2001 },
{ event: "Thomas Christiansen wird Torschützenkönig der Bundesliga", year: 2003 },
{ event: "Das Spiel Borussia Mönchengladbach gegen Borussia Dortmund erregt durch 5 erteilte Elfmeter Aufsehen", year: 1965 },
{ event: "Das Bundesliga-Spiel Hertha BSC gegen den 1. FC Köln findet vor 88.075 Zuschauern statt", year: 1969 },
{ event: "Wael Mohya wird mit 17 Jahre und 2 Monaten zum jüngsten Torschützen der Bundesliga-Geschichte", year: 2026 },
{ event: "Ousmane Dembele streikt sich von Borussia Dortmund zum FC Barcelona", year: 2017 },
{ event: "Javi Martinez wechselt für bahnbrechende 40 Mio. € zum FC Bayern", year: 2012 },
{ event: "Moritz Stoppelkamp erzielt für den SC Paderborn ein Tor aus 82,3 Metern", year: 2014 },
{ event: "Der Hamburger SV steigt das erste Mal aus der Bundesliga ab",year: 2018 },
{ event: "Jürgen Klinsmann tritt nach seiner Auswechslung eine Werbetonne kaputt", year: 1997 },
{ event: "Lionel Messi erzielt 91 Tore in einem Kalenderjahr", year: 2012 },
{ event: "Rudi Völler sorgt im Interview mit Waldemar Hartmann für den Weißbier-Eklat", year: 2003 },
{ event: "Jan Löhmannsröben sagt im Interview nach dem Spiel, dass der Schiedsrichter Cornflakes zählen gehen soll", year: 2018 },
{ event: "Stefan Effenberg zeigt Deutschland-Fans den Mittelfinger", year: 1994 },
{ event: "Die Fans von Borussia Dortmund zeigen auf einem Banner Dietmar Hopp im Fadenkreuz", year: 2018 },
{ event: "RB Leipzig steigt in die Bundesliga auf", year: 2016 },
{ event: "Die Fans vom FC Bayern München zeigen Koan Neuer-Plakate", year: 2011 },
{ event: "Der Fernsehsender Premiere wird zu Sky", year: 2009 },
{ event: "Raul wechselt zum FC Schalke 04 in die Bundesliga", year: 2010 },
{ event: "Roberto Carlos trifft aus 35 Metern per Außenrist-Freistoß", year: 1997 },
{ event: "Der FC Bayern München holt die 10. Bundesliga-Meisterschaft", year: 1987 },
{ event: "Der FC Bayern München holt die 20. Bundesliga-Meisterschaft", year: 2010 },
{ event: "Der FC Bayern München holt die 30. Bundesliga-Meisterschaft", year: 2020 },
{ event: "Der Hamburger SV holt den Europapokal der Landesmeister", year: 1983 },
{ event: "Gerald Asamoah ist auf dem FIFA-Cover", year: 2002 },
{ event: "England qualifiziert sich für eine Weltmeisterschaft dank des Freistoßtreffers von David Beckham gegen Griechenland", year: 2001 },
{ event: "Ivan Zamorano trägt inoffiziell die Rückennummer 1+8", year: 1997 },
{ event: "Juventus Turin muss aufgrund von Spielmanipulation zwangsabsteigen", year: 2006 },
{ event: "Birgit Prinz erzielt ihren 100. Treffer für die Nationalmannschaft", year: 2006 },
{ event: "Marco van Basten gewinnt seinen dritten Ballon D'Or", year: 1992 },
{ event: "Christoph Kramer erzielt ein Eigentor aus 45 Metern", year: 2014 },
{ event: "Das Westfalenstadion wird umgebaut und zum größten Stadion der Bundesliga", year: 2003 },
{ event: "Roy Keane foult Alf Inge Haaland und beendet langfristig mehr oder weniger seine Karriere", year: 1997 },
{ event: "Der SV Waldhof Mannheim nennt sich für 190.000 DM in Chio Waldhof 07 um", year: 1972 },
{ event: "Lothar Matthäus bestreitet sein 100. Länderspiel", year: 1993 },
{ event: "Miroslav Klose bestreitet sein 100. Länderspiel", year: 2010 },
{ event: "Franz Beckenbauer bestreitet sein 100. Länderspiel", year: 1976 },
{ event: "Lothar Matthäus debütiert für die deutsche Nationalmannschaft", year: 1980 },
{ event: "Jürgen Klinsmann debütiert für die deutsche Nationalmannschaft", year: 1987 },
{ event: "Franz Beckenbauer debütiert für die deutsche Nationalmannschaft", year: 1965 },
{ event: "Michael Ballack debütiert für die deutsche Nationalmannschaft", year: 1999 },
{ event: "Mesut Özil debütiert für die deutsche Nationalmannschaft", year: 2009 },
{ event: "Oliver Bierhoff debütiert für die deutsche Nationalmannschaft", year: 1996 },
{ event: "Der VfL Wolfsburg steigt erstmals in die 1. Bundesliga auf", year: 1997 },
{ event: "Der 1. FSV Mainz 05 steigt erstmals in die 1. Bundesliga auf", year: 2004 },
{ event: "Der SC Freiburg steigt erstmals in die 1. Bundesliga auf", year: 1993 },
{ event: "Peter Neururer führt den 1. FC Saarbrücken in die 1. Bundesliga", year: 1992 },
{ event: "Peter Neururer wird geboren", year: 1955 },
{ event: "Das Dynamo Dresden Wappen bekommt einen grünen Anstrich", year: 1990 },
{ event: "Der FC Bayern München holt seinen 1000. Bundesliga Sieg", year: 2015 },
{ event: "Borussia Dortmund steigt erstmals aus der Bundesliga ab", year: 1972 },
{ event: "Der SV Werder Bremen steigt erstmals aus der Bundesliga ab", year: 1980 },
{ event: "Eintracht Frankfurt steigt erstmals aus der Bundesliga ab", year: 1996 },
{ event: "Der SC Paderborn schafft den Durchmarsch von der 3. Liga in die 1. Bundesliga", year: 2019 },
{ event: "Die Wechselabsicht des 13 Jährigen Lionel Messi zum FC Barcelona wird schriftlich auf einer Serviette festgehalten", year: 2000 },
{ event: "Ronaldo Nazario wechselt zu Real Madrid", year: 2002 },
{ event: "Ronaldo Nazario wird geboren", year: 1976 },
{ event: "Ronaldinho wird geboren", year: 1980 },
{ event: "Ronaldinho wechselt zum FC Barcelona", year: 2003 },
{ event: "Boris Vukčević erleidet bei einem Autounfall auf dem Weg ins Training lebensgefährliche Kopfverletzungen", year: 2012 },
{ event: "Ralf Rangnick wird Cheftrainer der TSG 1899 Hoffenheim", year: 2006 },
{ event: "Alemannia Aachen steigt erstmals in die Bundesliga auf", year: 1967 },
{ event: "Jens Lehmann beendet seine Profikarriere", year: 2010 },
{ event: "Karl-Heinz Körbel absolviert sein 600. Bundesliga Spiel", year: 1991 },
{ event: "Hertha BSC II erreicht das DFB-Pokalfinale", year: 1993 },
{ event: "Hertha BSC stellt sein neues Maskottchen Herthinho vor", year: 1999 },
{ event: "Borussia Dortmund stellt sein neues Maskottchen Emma vor", year: 2005 },
{ event: "Borussia Mönchengladbach stellt sein neues Maskottchen Jünter vor", year: 1999 },
{ event: "Gerald Asamoah erlebt beim Relegationsspiel gegen Energie Cottbus massive rassistische Angriffe", year: 1997 },
{ event: "Athletic Bilbao schlägt den FC Barcelona in der ersten spanischen Liga mit 12:1", year: 1931 },
{ event: "Der FC Turin schlägt Forza e Coraggio Alessandria in der ersten italienischen Liga mit 10:0", year: 1948 },
{ event: "Der FC Sochaux-Montbéliard schlägt den FC Valenciennes in der ersten französischen Liga mit 12:1", year: 1935 },
{ event: "Red Bull Salzburg entsteht aus der Übernahme der SV Austria Salzburg", year: 2005 },
{ event: "Aus dem englischen Traditionsverein Wimbledon F.C. entsteht endgültig der Milton Keynes Dons F.C.", year: 2004 },
{ event: "Georgien qualifiziert sich das erste Mal für eine Europameisterschaft", year: 2024 },
{ event: "Andreas Neuendorf darf erstmals seinen Künstlernamen Zecke auf dem Trikot tragen", year: 2002 },
{ event: "Hertha BSC Präsident Kay Bernstein verstirbt unerwartet", year: 2024 },
{ event: "Julian Schuster wird Cheftrainer des SC Freiburg", year: 2024 },
{ event: "Patrick Ebert und Kevin Prince Boateng treten nachts betrunken Autospiegel ab", year: 2009 },
{ event: "FC Bayern Profi Christian Lell wird gegenüber seiner Freundin vor einer Disco gewalttätig", year: 2007 },
{ event: "Die SpVgg Unterhaching geht an die Börse", year: 2019 },
{ event: "Die US-amerikanischen Schauspieler Ryan Reynolds und Rob McElhenney kaufen den walisischen Traditionsverein Wrexham AFC", year: 2020 },
{ event: "Wayne Rooney wechselt zu Manchester United", year: 2004 },
{ event: "Kickbase wird gegründet", year: 2013 },
{ event: "Oliver Kahn wird geboren", year: 1969 },
{ event: "Der Film \"Das Wunder von Bern\" kommt in die Kinos", year: 2003 },
{ event: "Frank Rijkaard spuckt Rudi Völler in die Haare", year: 1990 },
{ event: "Das Ausziehen des Trikots nach einem Tor wird ab sofort mit Gelb bestraft", year: 2004 },
{ event: "Jens Lehmann geht mit einer Kettensäge auf die Garage seines Nachbars los", year: 2022 },
{ event: "Senegal nimmt erstmals an einer FIFA-Fußball-Weltmeisterschaft teil", year: 2002 },
{ event: "Ghana nimmt erstmals an einer FIFA-Fußball-Weltmeisterschaft teil", year: 2006 },
{ event: "Robert Baggio verschießt den entscheidenen Elfmeter gegen Brasilien in den USA", year: 1994 },
{ event: "Scheich Mansour bin Zayid Al Nahyan übernimmt Manchester City", year: 2008 },
{ event: "Alexander Meier wird erstmals Torschützenkönig in der Bundesliga", year: 2015 },
{ event: "Mats Hummels feiert sein erstes A-Länderspiel für Deutschland", year: 2010 },
{ event: "Philipp Lahm wird an den VfB Stuttgart ausgeliehen", year: 2003 },
{ event: "Union Berlin verpflichtet Robin Gosens als Rekordtransfer", year: 2023 },
{ event: "Der VfL Bochum veröffentlicht sein bekanntes buntes Fußballtrikot mit dem Sponsor Faber", year: 1997 },
{ event: "Robert Lewandowski wechselt zu Borussia Dortmund", year: 2010 },
{ event: "Dynamo Kiew gewinnt gegen Ferencvaros Budapest den Europapokal der Pokalsieger", year: 1975 },
{ event: "Kevin Keegan gewinnt erstmals den Ballon D'Or", year: 1978 },
{ event: "Zlatko Cajkovski wird Trainer des FC Bayern München", year: 1963 },
{ event: "Walter Frosch wird mit Zigaretten in den Stutzen interviewt", year: 2007 },
{ event: "Vincent Kompany wird Trainer beim FC Bayern München", year: 2024 },
{ event: "Der 1.FC Heidenheim steigt zum ersten Mal in die Bundesliga auf", year: 2023 },
{ event: "Mario Balotelli jubelt mit einem T-Shirt und der Aufschrift \"Why always me\"", year: 2011 },
{ event: "Pep Guardiola wird geboren", year: 1971 },
{ event: "Ottmar Hitzfeld wird geboren", year: 1949 },
{ event: "Die erste FIFA-Frauen-Fußball-Weltmeisterschaft findet in China statt", year: 1991 },
{ event: "Petr Cech prallt mit Robert Huth zusammen und trägt fortan nur noch Helm", year: 2006 },
{ event: "Kevin Kampl gießt Red Bull in den DFB-Pokal", year: 2023 },
{ event: "Sabrina Wittmann wird als erste Frau Cheftrainerin im deutschen Profifußball", year: 2024 },
{ event: "Union Berlin Trainer Nenad Bjelica verteilt eine Backpfeife an Leroy Sané", year: 2024 },
{ event: "Lukas Podolski feiert sein Bundesliga-Debüt", year: 2003 },
{ event: "Hans-Jörg Butt erzielt sein erstes Bundesliga-Tor", year: 1998 },
{ event: "Der FC Barcelona schlägt bei der \"Remontada\" Paris St. Germain mit 6:1", year: 2017 },
{ event: "Der Staat Katar steigt bei Paris St. Germain ein", year: 2011 },
{ event: "Die Türkei wird Dritter bei einer FIFA-Fußball-Weltmeisterschaft", year: 2002 },
{ event: "Cristiano Ronaldo kehrt zu Manchester United zurück", year: 2021 },
{ event: "Ruud van Nistelrooy wechselt zum Hamburger SV", year: 2010 },
{ event: "Luka Modric wechselt zum AC Mailand", year: 2025 },
{ event: "Aleksander Ceferin wird UEFA-Präsident", year: 2016 },
{ event: "Gianni Infantino wird FIFA-Präsident", year: 2016 },
{ event: "Bastian Schweinsteiger wechselt zu Manchester United", year: 2015 },
{ event: "Bastian Schweinsteiger wird geboren", year: 1984 },
{ event: "Manuel Gräfe leitet sein letztes Bundesliga-Spiel", year: 2021 },
{ event: "Deniz Aytekin gibt sein Bundesliga-Debüt als Schiedsrichter", year: 2008 },
{ event: "Ousmane Dembélé gewinnt den Ballon D'Or", year: 2025 },
{ event: "Der FC Bayern München feuert Oliver Kahn und Hasan Salihamidzic", year: 2023 },
{ event: "Der FC Bayern München steigt in die 1. Bundesliga auf", year: 1965 },
{ event: "Uli Hoeneß wird Manager beim FC Bayern München", year: 1979 },
{ event: "Julian Nagelsmann wird DFB-Nationaltrainer", year: 2023 },
{ event: "Lamine Yamal feiert beim FC Barcelona sein Pflichtspieldebüt", year: 2023 },
{ event: "Gerd Müller wechselt in die USA zu den Fort Lauderdale Strikers", year: 1979 },
{ event: "Der FC Bayern München gewinnt die Champions League ohne Niederlage", year: 2020 },
{ event: "Gerd Müller wird geboren", year: 1945 },
{ event: "Manchester City gewinnt zum ersten Mal die englische Meisterschaft", year: 1937 },
{ event: "Toni Kroos wechselt zu Real Madrid", year: 2014 },
{ event: "Die erste Panini-Kollektion ist in Deutschland erhältlich", year: 1978 },
{ event: "Tasmania Berlin spielt die schlechteste Bundesliga-Saison aller Zeiten", year: 1966 },
{ event: "Anthony Ujah macht seinen Geißbock-Jubel mit Hennes VIII.", year: 2015 },
{ event: "Tim Wiese feiert sein WWE-Debüt", year: 2016 },
{ event: "", year: 2016 },
{ event: "Lukas Podolski wechselt zum FC Bayern München", year: 2006 },
{ event: "Die TSG 1899 Hoffenheim wird Herbstmeister in der Bundesliga", year: 2008 },
{ event: "Rund 30.000 Fans von Eintracht Frankfurt erobern das Camp Nou bei einem Champions-League-Spiel", year: 2022 },
{ event: "Eintracht Frankfurt gewinnt gegen die Glasgow Rangers die Europa-League", year: 2022 },
{ event: "Jamal Musiala feiert beim FC Bayern München sein Pflichtspieldebüt", year: 2020 },
{ event: "Thomas Schaaf verlässt den SV Werder Bremen als Cheftrainer", year: 2013 },
{ event: "Borussia Dortmund gewinnt mit Ottmar Hitzfeld die Champions-League", year: 1997 },
{ event: "Olympique de Marseille gewinnt die erste Ausgabe der neuen Champions League", year: 1993 },
{ event: "Marcello Lippi gewinnt mit Juventus Turin die Champions League", year: 1996 },
{ event: "Mesut Özil posiert erstmals öffentlich auf einem Foto mit Recep Tayyip Erdogan", year: 2018 },
{ event: "Es findet die erste Ballon D'Or Verleihung für den Frauenfußball statt", year: 2018 },
{ event: "Gareth Bale posiert nach einem Länderspiel mit einer \"Wales. Golf. Madrid. In that Order.\"-Flagge", year: 2021 },
{ event: "Der FC Schalke 04 holt ein 0:4 gegen Borussia Dortmund zu einem 4:4 auf", year: 2017 },
{ event: "Jürgen Klinsmann übernimmt den Trainerposten bei Hertha BSC", year: 2019 },
{ event: "Luka Modric wechselt zu Real Madrid", year: 2012 },
{ event: "Union Berlin steigt zum ersten Mal in der Vereinsgeschichte in die Bundesliga auf", year: 2019 },
{ event: "Luis Suárez wechselt zum FC Barcelona", year: 2014 },
{ event: "Zwergenstaat San Marino feiert den allerersten Sieg in einem Länderspiel", year: 2004 },
{ event: "Zlatan Ibrahimovic wechselt zum FC Barcelona", year: 2009 },
{ event: "West Ham United zieht in das neu umgebaute London Stadium um und verlässt damit den Upton Park", year: 2016 },
{ event: "Kevin De Bruyne wechselt zu Manchester City", year: 2015 },
{ event: "Florentino Pérez wird Präsident von Real Madrid", year: 2000 },
{ event: "Jürgen Klopp wird neuer Cheftrainer des FC Liverpool", year: 2015 },
{ event: "Der legendäre Fangesang \"Glory Glory Man United\" wird veröffentlicht", year: 1983 },
{ event: "Mikel Arteta wird neuer Cheftrainer des FC Arsenal", year: 2019 },
{ event: "Die neue Vereinshymne \"Stern des Südens\" des FC Bayern München wird veröffentlicht", year: 1998 },
{ event: "Die Vereinshymne \"¡Hala Madrid!\" wird erstmals veröffentlicht", year: 1952 },
{ event: "Der DFB führt die eingleisige 3. Liga in Deutschland ein", year: 2008 },
{ event: "Der DFB führt die eingleisige 2. Bundesliga in Deutschland ein", year: 1981 },
{ event: "Das erste offizielle deutsche Supercup-Finale findet statt", year: 1987 },
{ event: "Harry Kane wechselt zum FC Bayern München", year: 2023 },
{ event: "Harry Kane wird geboren", year: 1993 },
{ event: "In der Münchner Allianz Arena wird erstmals der Audi Cup ausgetragen", year: 2009 },
{ event: "Francesco Totti feiert mit nur 16 Jahren sein Debüt für die AS Rom", year: 1993 },
{ event: "VfL Wolfsburg-Profi Junior Malanda kommt bei einem Autounfall ums Leben", year: 2015 },
{ event: "Emiliano Sala stirbt bei einem Flugzeugabsturz, als er auf dem Weg war, seinen neuen Vertrag bei Cardiff City zu unterschreiben", year: 2019 },
{ event: "FC Liverpool-Profi Diogo Jota stirbt mit seinem Bruder bei einem Autounfall", year: 2025 },
{ event: "Ibrahim Sunday wird der erste Afrikaner, der je in der Bundesliga spielt", year: 1975 },
{ event: "Eric Wynalda läuft als erster US-Amerikaner in der Bundesliga für den 1. FC Saarbrücken auf", year: 1992 },
{ event: "Yasuhiko Okudera wird der erste Japaner in der Bundesliga, als er für den 1. FC Köln debütiert", year: 1977 },
{ event: "Chen Yang wird der erste Chinese in der Bundesliga, als er für Eintracht Frankfurt debütiert", year: 1998 },
{ event: "Dave Mitchell wird der erste Australier in der Bundesliga, als er für Eintracht Frankfurt debütiert", year: 1985 },
{ event: "Ali Daei wird der erste Iraner in der Bundesliga, als er für Arminia Bielefeld debütiert", year: 1997 },
{ event: "Henrikh Mkhitaryan wird der erste Armenier in der Bundesliga, als er für Borussia Dortmund debütiert", year: 2013 },
{ event: "Stefan Kießling erzielt ein berüchtigtes Phantomtor, als sein Kopfball durch ein Loch im Außennetz ins Tor geht", year: 2013 },
{ event: "Im \"Büchsenwurfspiel\" wird Inter-Profi Roberto Boninsegna von einer Cola-Dose getroffen und muss verletzt vom Platz", year: 1971 },
{ event: "Der VfL Wolfsburg wechselt im DFB-Pokal gegen den SC Preußen Münster versehentlich ein sechstes Mal ein und verliert das Spiel am grünen Tisch", year: 2021 },
{ event: "Andrés Escobar unterläuft bei der WM ein Eigentor – wenige Tage später wird er in Kolumbien vom Drogenkartell ermordet", year: 1994 },
{ event: "Schiedsrichter Janny Sikazwe sorgt beim Afrika-Cup für einen Eklat, als er das Spiel Tunesien gegen Mali gleich zweimal zu früh abpfeift", year: 2022 },
{ event: "Die UEFA führt mit der \"Conference League\" einen neuen internationalen Klubwettbewerb ein", year: 2021 },
{ event: "Die UEFA führt ein neues Champions-League-Format mit mehr Spielen und ohne \"klassische\" Gruppenphase ein", year: 2024 },
{ event: "Der FC Schalke 04 wird in der Bundesliga sportlich Letzter – bleibt allerdings dank der Ligenerweiterung im Oberhaus", year: 1965 },
{ event: "Rudi Assauer übernimmt erstmals das Amt des Managers beim FC Schalke 04", year: 1981 },
{ event: "Der FC Schalke 04 steigt zum ersten Mal aus der Bundesliga ab", year: 1981 },
{ event: "Cristiano Ronaldo gründet seine eigene Modelinie mit dem Namen \"CR7\"", year: 2006 },
{ event: "Giovane Élber tapet sich nach einer Gelben Karte im Spiel gegen 1860 München demonstrativ den Mund zu, um einen Platzverweis zu vermeiden", year: 1997 },
{ event: "Lothar Matthäus sorgt für Aufsehen, als er im Leipziger Stadtpokal für Lokomotive Leipzig aufläuft", year: 2005 },
  { event: "Ferenc Puskás wird geboren", year: 1927 },
  { event: "Das neue Sportmagazin \"kicker\" veröffentlicht seine Erstausgabe", year: 1920 },
  { event: "Das neue Fußballmagazin \"11Freunde\" veröffentlicht seine Erstausgabe", year: 2000 },
  { event: "Die \"Sportschau\" feiert seine Erstausstrahlung im ZDF", year: 1952 },
  { event: "Die Talkshow \"Doppelpass\" feiert seine Erstausstrahlung auf Sport1", year: 1991 },
  { event: "Die Partie zwischen dem SV Werder Bremen und dem 1.FC Köln wird als erstes Bundesliga-Spiel live im Fernsehen übertragen", year: 1969 },
  { event: "Lothar Matthäus heiratet seine Erste (von Fünf) Ehefrau Marianne", year: 1981 },
  { event: "Cristiano Ronaldo versteckt während einer Pressekonferenz mit Portugal Produkte des Turniersponsors \"Coca Cola\" und sorgt damit für Aufsehen", year: 2021 },
  { event: "Philipp Lahm beendet seine aktive Laufbahn", year: 2017 },
  { event: "Thomas Hitzelsperger outet sich als Erster ehemaliger deutscher Nationalspieler als homosexuell", year: 2014 },
  { event: "Uli Hoeneß wird wegen Steuerhinterziehung in Höhe von über 28 Mio. € zu einer Haftstrafe von 3,5 Jahren verurteilt", year: 2014 },
  { event: "FC Bayern München-Profi Breno wird wegen Brandstiftung zu einer Haftstrafe von 3 Jahren und 9 Monaten verurteilt", year: 2012 },
  { event: "Robert Enke nimmt sich im Alter von 32 Jahren das Leben", year: 2009 },
  { event: "Die Mannschaft des brasilianischen Erstligisten Chapocoense stürzt mit dem Flugzeug über den Bergen von Kolumbien ab", year: 2016 },
  { event: "Die Mannschaft von Manchester United stürzt bei der Landung auf dem Flughafen München-Riem ab", year: 1958 },
  { event: "Der Fan-Song \"Es gibt nur ein Rudi Völler\" wird veröffentlicht", year: 2002 },
  { event: "Die FIFA vergibt die Weltmeisterschaft 2022 nach Katar", year: 2010 },
  { event: "Petr Čech verletzt sich gegen den FC Reading und beschließt fortan nur noch mit Helm zu spielen", year: 2006 },
  { event: "Der russische Oligarch Roman Abramovich kauft den FC Chelsea", year: 2003 },
  { event: "Die Fußball-Website \"transfermarkt.de\" geht erstmals online", year: 2000 },
  { event: "Das erste FIFA-Videospiel von EA Sports kommt auf den Markt", year: 1993 },
  { event: "DFB-Präsident Wolfgang Niersbach tritt nach der \"Uhr-Affäre\" von seinen Ämtern zurück", year: 2015 },
  { event: "Das \"Aktuelle Sportstudio\" feiert seine Erstausstrahlung im damaligen NWDR", year: 1963 },
  { event: "Jan Koller muss ab der 67. im Bundesliga-Spiel gegen den FC Bayern München ins Tor - er pariert ohne Fehler", year: 2002 },
  { event: "Der FC St. Pauli steigt zum ersten Mal in die 1. Bundesliga auf ", year: 1976 },
  { event: "Franck Ribéry wechselt zum FC Bayern München", year: 2007 },
  { event: "Hennes I. tritt zum ersten Mal als Maskottchen des 1.FC Köln auf", year: 1950 },
  { event: "Die rote Karte wird in der Bundesliga eingeführt", year: 1970 },
  { event: "Die Bundesliga führt eine Spielsperre nach der fünften gelben Karte ein", year: 1991 },
  { event: "Christian Eriksen kollabiert auf dem Spielfeld aufgrund eines plötzlichen Herztods und überlebt nur knapp", year: 2021 },
  { event: "Andreas Möller wechselt vom FC Schalke 04 zu Rivale Borussia Dortmund und wird dadurch zur Hassfigur", year: 2000 },
  { event: "Youssoufa Moukoko debütiert mit 15 Jahren und 364 Tagen in der Bundesliga für Borussia Dortmund", year: 2020 },
  { event: "Gianluigi Donnarumma debütiert mit 16 Jahren für den AC Mailand in der Serie A", year: 2015 },
  { event: "Borussia Mönchengladbach besiegt Borussia Dortmund in der Bundesliga mit 12:0", year: 1978 },
  { event: "Oliver Kahn wird von einem Fan des SC Freiburg mit einem Golfball im Gesicht getroffen", year: 2000 },
  { event: "Paolo Guerrero grätscht Torhüter Sven Ulreich an der Eckfahne hüfthoch um und erhält eine Sperre von acht Spielen", year: 2012 },
  { event: "Die SK Rapid Wien gewinnt den Vorgänger des heutigen DFB-Pokals (Tschammer-Pokal)", year: 1939 },
  { event: "Der angetrunkene Schiedsrichter Wolf-Dieter Ahlenfelder pfeift im Bundesliga-Spiel zwischen dem SV Werder Bremen und Hannover 96 bereits nach 32 Minuten zur Halbzeit", year: 1975 },
  { event: "Jens Lehmann pinkelt beim Spiel vom VfB Stuttgart gegen Bayer 04 Leverkusen, nachdem er hinter die Werbebande geklettert ist, hinter die Werbetonne", year: 2009 },
  { event: "Max Kruse gewinnt 75.000€ beim Poker spielen und vergisst es kurz darauf im Taxi", year: 2016 },
  { event: "Deutschland gewinnt den Confed-Cup", year: 2017 },
  { event: "Dani Alves wird Opfer eines rassistischen Vorfalls im Spiel FC Villareal gegen den FC Barcelona, indem er mit Bananen beworfen wird. Er isst diese kurzerhand einfach", year: 2014 },
  { event: "Der FC Bayern München beruft eine Pressekonferenz ein – um Journalisten für Kritik an Spielern öffentlich zu rügen", year: 2018 },
  { event: "Christoph Daum willigt aufgrund seines \"absolut reinem Gewissen\" einem Drogentest zu, der sich als postiv herausstellt", year: 2000 },
  { event: "Giovanni Trappatoni hält eine Wutrede bei einer Pressekonferenz, in der legendäre Zitate wie \"Was erlauben Strunz?\" oder \"Ich habe fertig!\"", year: 1998 },
  { event: "Die Italiener laufen als politisches Statement für Mussolini bei einer WM im schwarzen Trikot auf", year: 1938 },
  { event: "Arjen Robben wechselt zum FC Bayern München", year: 2009 },
  { event: "Die umstrittene Bronzestatue am Flughafen Madeiras von Cristiano Ronaldo wird enthüllt", year: 2017 },
  { event: "Neymar wechselt zum FC Barcelona", year: 2013 },
  { event: "Paul, die Krake sagte bei einer WM alle Deutschland-Spiele korrekt voraus", year: 2010 },
  { event: "Uruguays José Batista sieht im WM-Spiel gegen Schottland nach 56 Sekunden die Rote Karte – bis heute Rekord", year: 1986 },
  { event: "Andrés Iniesta wechselt zu Vissel Kobe", year: 2018 },
  { event: "Sergej W. verübt einen Anschlag auf den Mannschaftsbus von Borussia Dortmund", year: 2017 },
  { event: "Gerd Müller absolviert sein letztes Bundesliga-Spiel für den FC Bayern München", year: 1979 },
  { event: "Lionel Messi holt seinen allerersten Champions-League-Titel", year: 2006 },
  { event: "Lionel Messi wird mit Argentinien zum ersten Mal Weltmeister", year: 2022 },
  { event: "Cristiano Ronaldo wird mit Portugal zum ersten Mal Europameister", year: 2016 },
  { event: "Luis Figo wechselt vom FC Barcelona zum Ligarivalen Real Madrid", year: 2000 },
  { event: "Deutschland wird zum zweiten Mal Weltmeister", year: 1974 },
  { event: "Spanien wird zum ersten Mal Europameister", year: 1964 },
  { event: "Spanien wird zum ersten Mal Weltmeister", year: 2010 },
  { event: "Fabio Cannavaro gewinnt den Ballon D'Or", year: 2006 },
  { event: "Manuel Neuer wechselt vom FC Schalke 04 zum FC Bayern München", year: 2011 },
  { event: "Pelé schießt sein allererstes Länderspieltor", year: 1957 },
  { event: "Miroslav Klose feiert sein Länderspiel-Debüt für Deutschland", year: 2001 },
  { event: "Brasilien wird zum fünften Mal Weltmeister", year: 2002 },
  { event: "Eden Hazard wechselt vom FC Chelsea London zu Real Madrid", year: 2019 },
  { event: "Kylian Mbappé wechselt von Paris St. Germain zu Real Madrid", year: 2024 },
  { event: "Joachim Löw wird Cheftrainer der deutschen Nationalmannschaft", year: 2006 },
  { event: "Jürgen Klopp wird Cheftrainer von Borussia Dortmund", year: 2008 },
  { event: "Thomas Tuchel wird Cheftrainer vom FC Bayern München", year: 2023 },
  { event: "Pep Guardiola wird Cheftrainer vom FC Barcelona", year: 2008 },
  { event: "Lamine Yamal macht sein Profi-Debüt für den FC Barcelona", year: 2023 },
  { event: "Deutschland besiegt Costa Rica bei einem Fußball-Weltmeisterschaftsspiel dank Lahm, Klose und Frings mit 4:2", year: 2006 },
  { event: "Südafrika ist Gastgeber einer Fußball-Weltmeisterschaft", year: 2010 },
  { event: "Borussia Dortmund gewinnt zum ersten Mal die Deutsche Meisterschaft", year: 1956 },
  { event: "Bayer 04 Leverkusen gewinnt zum ersten Mal die Bundesliga-Meisterschaft", year: 2024 },
  { event: "Uruguay wird zum ersten Mal Fußball-Weltmeister", year: 1930 },
  { event: "Der Videobeweis (VAR) kommt zum ersten Mal bei einer Fußball-Weltmeisterschaft zum Einsatz", year: 2018 },
  { event: "Just Fontaine trifft zwölf Mal bei einer Fußball-Europameisterschaft", year: 1960 },
  { event: "Gianni Infantino wird neu zum FIFA-Präsidenten gewählt", year: 2016 },
  { event: "Julian Nagelsmann wird Cheftrainer der deutschen Nationalmannschaft", year: 2023 },
  { event: "Deutschland besiegt Argentinien in einem WM-KO-Spiel mit 4:0", year: 2010 },
  { event: "Diego Maradona wird Cheftrainer der argentinischen Nationalmannschaft", year: 2008 },
  { event: "Carlo Ancelotti wird Cheftrainer der brasilianischen Nationalmannschaft", year: 2025 },
  { event: "Die neugegründete Youth-League geht erstmals an den Start", year: 2013 },
  { event: "Iker Casillas beendet seine aktive Laufbahn", year: 2020 },
  { event: "Marc-André ter Stegen wechselt zum FC Barcelona", year: 2014 },
  { event: "Leicester City gewinnt sensationell die Premier League", year: 2016 },
  { event: "Der VfL Wolfsburg gewinnt zum ersten Mal unter Felix Magath die Bundesliga", year: 2009 },
  { event: "Die erste Bundesliga-Saison wird ausgetragen", year: 1963 },
  { event: "Die erste Serie A Saison wird ausgetragen", year: 1929 },
  { event: "Thomas Müller feiert sein Bundesliga-Debüt für den FC Bayern München", year: 2008 },
  { event: "Pep Guardiola wird Cheftrainer des FC Bayern München", year: 2013 },
  { event: "Kevin Großkreutz bewirft einen Fußball-Fan mit einem Döner", year: 2014 },
  { event: "Juventus Turin gewinnt zum ersten Mal die Serie A", year: 1905 },
  { event: "Inter Mailand gewinnt zum ersten Mal die Serie A", year: 1910 },
  { event: "Olympique Lyon gewinnt zum ersten Mal die Ligue 1", year: 2002 },
  { event: "Paris St. Germain gewinnt zum ersten Mal die Ligue 1", year: 1986 },
  { event: "Cristiano Ronaldo wechselt nach Saudi-Arabien", year: 2023 },
  { event: "Stéphanie Frappart pfeift als erste Frau ein WM-Spiel der Männer", year: 2022 },
  { event: "Der FC Bayern München gewinnt zum ersten Mal eine Bundesliga-Meisterschaft", year: 1969 },
  { event: "Cristiano Ronaldo holt seinen allerersten Champions-League-Titel", year: 2008 },
  { event: "Der FC Bayern München wird gegründet", year: 1900 },
  { event: "Schottland und England bestreiten das erste offizielle Länderspiel", year: 1872 },
  { event: "Giuseppe Meazza schießt im WM-Halbfinale einen Elfmeter mit gerissenem Hosenbund", year: 1938 },  
  { event: "Ewald Lienen wird von Norbert Siegmann so schwer gefoult, dass er sich eine 25 cm lange Wunde zu zieht", year: 1981 },
  { event: "Bayer Uerdingen dreht ein 0:2 Rückstand gegen Dynamo Dresden im Europapokal innerhalbvon 30 Minuten zu einem 7:3", year: 1986 },
  { event: "Ajax Amsterdam gewinnt zum dritten Mal in Folge den Europapokal der Landesmeister", year: 1973 },
  { event: "Real Madrid gewinnt zum fünften Mal in Folge den Europapokal der Landesmeister", year: 1960 },
  { event: "Commodore wird Trikotsponsor des FC Bayern Münche ", year: 1984 },
  { event: "Carlsberg wird Trikotsponsor des FC Liverpool", year: 1992 },
  { event: "Unicef schmückt das Trikot des FC Barcelona", year: 2006 },
  { event: "Drittligist Arminia Bielefeld erreicht das DFB-Pokalfinale", year: 2025 },
  { event: "Der VfL Bochum dreht die 4:0 Hinspiel-Niederlage gegen Fortuna Düsseldorf im Elfmeterschießen in der Relegation und bleibt dadurch erstklassig", year: 2024 },
  { event: "Gareth Bale schießt das 2:1 Siegtor gegen den FC Barcelona, indem er über außen ins Seitenaus rennt und um Marc Bartra herum sprintet", year: 2014 },
  { event: "Mit DAZN kommt ein neuer Streaming-Anbieter auf den Markt, der den \"günstigsten Zehner aller Zeiten\" anbietet", year: 2016 },
  { event: "Roy Makaay erzielt nach 10,12 Sekunden das schnellste Champions-League Tor der Geschichte", year: 2007 },
  { event: "Roberto Carlos trifft aus ca. 35 Metern per direktem Freistoß mit enormen Schnitt gegen Frankreich", year: 1997 },
  { event: "Karl-Heinz \"Charly\" Körbel absolviert sein 602. und letztes Bundesliga-Spiel - einsamer Rekord", year: 1991 },
  { event: "Uli Hoeneß verschießt im Elfmeterschießen gegen die Tschechoslowakei \"deutlich in den Nachthimmel\"", year: 1976 },
  { event: "Karl-Heinz Rummenigge wird am Flughafen gestoppt, weil er zwei nicht deklarierte Rolex dabei hat, die er laut eigener Aussage als Geschenk von einem Freund erhalten hat an den er sich nicht mehr erinnern kann", year: 2013 },
  { event: "Lionel Messi verlässt den FC Barcelona", year: 2021 },
  { event: "Cristiano Ronaldo verlässt Real Madrid", year: 2018 },
  { event: "Russland stürmt unter Guus Hiddink und mit Arshavin ins EM-Halbfinale", year: 2008 },
  { event: "Real Madrid gewinnt die Champions-League zum 14. Mal", year: 2022 },
  { event: "Alexia Putellas gewinnt zum ersten Mal den Ballon D'Or", year: 2021 },
  { event: "Der TSV 1860 München gewinnt zum ersten Mal die Bundesliga", year: 1966 },
  { event: "Der FC Bayern München stellt mit 101 Toren einen Torrekord in der Bundesliga auf", year: 1972 },
  { event: "Kevin Keegan wechselt zum Hamburger SV", year: 1977 },
  { event: "Wayne Rooney beendet seine Karriere", year: 2021 },
  { event: "Zlatan Ibrahimović trifft im Freundschaftsspiel gegen England per Fallrückzieher aus ca. 35 Metern", year: 2012 },
  { event: "Deutschland wird zum zweiten Mal Weltmeister", year: 1974 },
  { event: "Veltins wird zum ersten Mal Sponsor beim FC Schalke 04", year: 1997 },
  { event: "Trainerlegende Sir Alex Ferguson beendet seine Trainerkarriere", year: 2013 },
  { event: "Pelé schießt sein allererstes Länderspieltor", year: 1957 },
  { event: "Der FC Barcelona dreht in der Champions-League gegen Paris St. Germain eine 4:0-Hinspielniederlage und gewinnt mit 6:1", year: 2017 },
  { event: "Eric Cantona wird nach einem Kung-Fu-Tritt gegen einen Fan für 8 Monate gesperrt", year: 1995 },
  { event: "Lionel Messi trifft kurz vor Schluss im El Clásico und hält sein Trikot vor der Real-Madrid-Kurve in die Luft", year: 2017 },
  { event: "Robin van Persie trifft per Flugkopfall als „fliegender Holländer“ gegen Spanien zum 1:1", year: 2014 },
  { event: "Ronaldinho trifft per Lupfer von der Mittellinie gegen England", year: 2002 },
  { event: "Luis Suárez beißt Georgio Chiellini bei einem WM-Spiel", year: 2014 },
  { event: "Antonin Panenka prägt mit seinem kunstvollen Elfmeter bei einer Europameisterschaft ganze Generationen", year: 1976 },
  { event: "Kroatien zieht in sein erstes WM-Finale ein", year: 2018 },
  { event: "England gewinnt gegen Kolumbien erstmals ein Elfmeterschießen bei einer Weltmeisterschaft", year: 2018 },
  { event: "Eintracht Frankfurt gewinnt gegen die Glasgow Rangers die Europa-League", year: 2022 },
  { event: "Paris St. Germain gewinnt zum ersten Mal die Champions-League", year: 2025 },
  { event: "Der FC Bayern München gewinnt zum ersten Mal das Sextuple", year: 2020 },
  { event: "Deutschland besiegt die Türkei im Halbfinale einer Europameisterschaft im Elfmeterschießen", year: 2008 },
  { event: "Sami Khedira feiert sein Debüt für die deutsche Nationalmannschaft", year: 2009 },
  { event: "Der FC Bayern München besiegt Borussia Dortmund im deutschen Champions-League-Finale", year: 2013 },
  { event: "Manchester United besiegt den FC Bayern München dank zwei Treffer in der Nachspielzeit", year: 1999 },
  { event: "Spanien wird U17-, U21- und A-Nationalmannschaft-Europameister im gleichen Jahr", year: 2024 }
];
